# Pytorch basic essential Tensor operations

### This notebook will be focused on methods mostly used in Linear Regression, Logistic Regression and PCA

An short introduction about PyTorch and about the chosen functions. 
- tensor.new_zeros
- tensor.argsort
- tensor.dot
- tensor.inverse
- torch.eig

In [0]:
# Import torch and other required modules
import torch

## Function 1 - tensor.new_zeros
This method returns a tensor of shape: `size` with values of `0`

* Method definition:

    `new_zeros(size, dtype=None, device=None, requires_grad=False)`

In [2]:
# Example 1 - 1-D array of zeros

tensor = torch.tensor((), dtype=torch.float64)

tensor.new_zeros(3,)

tensor([0., 0., 0.], dtype=torch.float64)

methods takes in the integer passed to it and creates a tensor shape based on the number on values passed

In [3]:
# Example 2 - 2D array of zeros

tensor.new_zeros((2, 3))

tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

As we passed two values to the method created a 2D array with _3 rows and 4 columns_

In [4]:
# Example 3 - what not to do
tensor.new_zeros(2.4, 4)

TypeError: ignored

The values passed to the method must be `integers`

* When to use this function?
> This function is used during the initialization phase for the `weight` and `bias` vectors.

## Function 2 - tensor.argsort()

It returns the indices that will sort the tensor in ascending order by value

* Method definition:

    `tensor.argsort(dim=-1, descending=False)`

In [5]:
# Example 1 - working example

# getting random values
a = torch.randn(1, 5)
print(a)

print("Argsort output - >", a.argsort())
print("Using these indices we can sort the same or some other array")

tensor([[ 0.4456, -1.4063, -1.0058,  0.1396,  0.6501]])
Argsort output - > tensor([[1, 2, 3, 0, 4]])
Using these indices we can sort the same or some other array


In [6]:
# Example 2 - sorting wrt to a specific dimension

b = torch.randn(3, 3)
print(b)

print("Argsort output - >\n", b.argsort(dim=1))

tensor([[-1.5377, -2.8598,  0.8973],
        [-1.0519,  0.1639,  0.0361],
        [ 0.4737, -1.0002, -0.9223]])
Argsort output - >
 tensor([[1, 0, 2],
        [0, 2, 1],
        [1, 2, 0]])


We can see that the output matrix consists of column-wise index value that would sort the array in ascending value

In [7]:
# Example 3 - What not to do

b.argsort(dim=2)

IndexError: ignored

The number of dimensions start from [0,..], taking that into consideration pass correct values to the attribute

* When to use this function?
> This function is mostly used during sorting of the eigenvalues and eigenvector matrices where the eigenvector matrix is to be sorted considering the eigenvalues vector

## Function 3 - tensor.dot

This method is used to calcluate the inner product of two tensors

* Method definition

    `tensor.dot(tensor)`

In [8]:
# Example 1 - working example

# creating two tensors
a = torch.tensor([12, 6])
b = torch.tensor([0, 8])

print("1D - Arrays")
print(a)
print(b)

print("Dot Product ->", a.dot(b).item())

1D - Arrays
tensor([12,  6])
tensor([0, 8])
Dot Product -> 48


In [9]:
# Example 2 - negative dot products

a = torch.tensor([-4, -6])
b = torch.tensor([-9, 8])

print("1D - Arrays")
print(a)
print(b)

print("Dot Product ->", a.dot(b).item())

1D - Arrays
tensor([-4, -6])
tensor([-9,  8])
Dot Product -> -12


In [10]:
# Example 3 - what not to do

# creating two tensors
a = torch.Tensor(2, 3)
b = torch.Tensor(13,)

print(a)
print(b)
print(a.dot(b))

tensor([[4.1241e-36, 0.0000e+00, 3.7835e-44],
        [0.0000e+00,        nan, 0.0000e+00]])
tensor([4.1241e-36, 0.0000e+00,        nan,        nan, 1.4013e-45, 0.0000e+00,
        4.4721e+21, 3.0104e+29, 7.1853e+22, 7.3123e+28, 6.2706e+22, 4.7428e+30,
        0.0000e+00])


RuntimeError: ignored

Make sure the tensors created are 1D arrays.

This method is commonly used to find out the inner product between two vectors.

## Function 4 - tensor.inverse

This method calculates the inverse of matrices

* Method definition

    `tensor.inverse(out=None)`

In [11]:
# Example 1 - working

a = torch.randn(3, 3)
print(a)

print("Inverse - >\n", a.inverse())

print("Let's check: ")
print("(a * a^-1 = I)\n", torch.round(a @ a.inverse()))

tensor([[-0.4842,  0.7683,  0.3045],
        [-1.6003,  1.3088,  1.1788],
        [ 1.6386,  0.9721, -1.5668]])
Inverse - >
 tensor([[150.0984, -70.4224, -23.8180],
        [ 27.0385, -12.1956,  -3.9218],
        [173.7494, -81.2148, -27.9805]])
Let's check: 
(a * a^-1 = I)
 tensor([[1., 0., -0.],
        [-0., 1., -0.],
        [0., 0., 1.]])


we can clearly see that the method calc

In [12]:
# Example 2 - working

a = torch.randn(5, 5)
print(a)

print("Inverse - >\n", a.inverse())

print("Let's check: ")
print("(a * a^-1 = I)\n", torch.round(a @ a.inverse()))

tensor([[-1.7362, -0.3326,  0.6628,  0.2947, -0.9987],
        [-0.9477,  0.3815,  0.2853, -0.5985, -1.0210],
        [ 0.0610, -0.3464, -0.8078, -1.6041, -0.4438],
        [ 0.3758, -0.1981, -0.8562, -1.6748,  0.0571],
        [-0.3132, -1.7599,  0.6055,  0.8133, -0.9457]])
Inverse - >
 tensor([[-1.1016,  0.8178, -0.3463,  0.0624,  0.4466],
        [-0.3402,  0.4169,  0.5741, -0.9619, -0.4183],
        [-0.4215,  1.8539, -4.7641,  4.2816,  0.9374],
        [ 0.0343, -0.8332,  2.2184, -2.5801, -0.3334],
        [ 0.7574, -0.5762, -2.0960,  2.2918, -0.1134]])
Let's check: 
(a * a^-1 = I)
 tensor([[1., 0., 0., 0., -0.],
        [-0., 1., -0., 0., 0.],
        [-0., 0., 1., 0., 0.],
        [-0., -0., -0., 1., 0.],
        [0., 0., 0., -0., 1.]])


Explanation about example

In [13]:
# Example 3 - what not to do

a = torch.randn(2, 3)
print(a)

print("Inverse - >\n", torch.inverse(a))


tensor([[ 0.4430,  0.3327, -0.9195],
        [-0.9209, -0.1211, -0.5152]])


RuntimeError: ignored

To calculate the inverse we need a square, non-singular matrix.

To get around this constraint as most of the data `X` features will not be a sqaure matrix we can use `.pinverse()` which uses `SVD` to calculate the inverse

## Function 5 - tensor.eig

It computes the eigenvalues and eigenvectors of a real square matrix.

* Method definition:

    `tensor.eig(eigenvectors=False, out=None)`

In [14]:
# Example 1 - working

a = torch.randn(2, 2)

values, vectors = a.eig(eigenvectors=True)
print("A: ", a)
print("Eigenvalues: ", values[:, 0])
print("Eigenvectors: \n", vectors)

A:  tensor([[-0.7812,  0.0647],
        [-0.1522, -0.7145]])
Eigenvalues:  tensor([-0.7479, -0.7479])
Eigenvectors: 
 tensor([[ 0.1837, -0.5145],
        [ 0.8376,  0.0000]])


This method returns a eigenvalues of shape (n×2), 1st column being the real eigenvalue and imaginary part being the 2nd column.

Eigenvector is of shape (nxn)

In [15]:
# Example 2 - working

b = torch.randn(3, 3)

values, vectors = b.eig(eigenvectors=True)
print("A: ", b)
print("Eigenvalues: ", values[:, 0])
print("Eigenvectors: \n", vectors)

A:  tensor([[-0.1045,  0.1150,  0.1820],
        [ 0.7622,  0.4583,  0.4238],
        [-0.6784, -1.4927, -0.5208]])
Eigenvalues:  tensor([-0.3558,  0.0944,  0.0944])
Eigenvectors: 
 tensor([[-0.6342, -0.0066, -0.1671],
        [ 0.2058, -0.3515, -0.3293],
        [ 0.7453,  0.8602,  0.0000]])


Eigenvalues and Eigenvectors of 3x3 matrix

In [16]:
# Example 3 - what not to do

c = torch.randn(3, 4)

values, vectors = c.eig(eigenvectors=True)
print("A: ", c)
print("Eigenvalues: ", values[:, 0])
print("Eigenvectors: \n", vectors)

RuntimeError: ignored

For computing the Eigen's of a given matrix, the matrix should be a square matrix.

* When to use this function?
> This function is very useful in dimensionality reduction such as PCA to compute the direction of maximum variance which can be used as a principal axis of projection.

## Conclusion

In this notebook we saw different useful and commonly used functions in machine learning

1) tensor.new_zeros - creating a new tensor of zeros.

2) tensor.argsort - get the array of index that will sort the given array.

3) tensor.dot - calculate the inner product between two vectors.

4) tensor.inverse - calculating inverse of matrices for solving system of linear equations.


5) torch.eig - calculating the magnitude and the unit vectors that isn't affected by the transformation applied to the whole space and which points to the direction of maximum of variance of the data.

## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for `torch.Tensor`: https://pytorch.org/docs/stable/tensors.html